### ISSUE TITLE
Configurable indent level

### ISSUE THREAD

**Issue by ben-eb** [ben-eb/perfectionist#10]
Ref: https://github.com/ben-eb/perfectionist/issues/7

This is an easy fix as the module calculates space from a multiplier.

https://github.com/ben-eb/perfectionist/blob/7bf13f05d637867aaa29470936cd21d3110f2243/src/getIndent.js#L5

**Comment by ben-eb** [comment]
Released as `1.3.0`.

**Comment by Kikobeats** [comment]
what about do it in the CLI?

**Comment by ben-eb** [comment]
@Kikobeats There's no alias, but the option is passed directly through:

```
perfectionist --indentSize 8 input.css > output.css
```

**Comment by Kikobeats** [comment]
oh, perfect. Maybe could be useful update CLI help message :)

**Comment by ben-eb** [comment]
Yeah; PR welcome. :smile:
