### ISSUE TITLE
Support SCSS

### ISSUE THREAD

**Issue by yisibl** [ben-eb/perfectionist#15]
Like:

input:

```scss
$foo:30px;$bar:20px;
```

output:

```scss
$foo: 30px;
$bar: 20px;
```

**Comment by sindresorhus** [comment]
Should be possible now that PostCSS supports custom parsers:
https://github.com/postcss/postcss/#custom-syntaxes
https://github.com/postcss/postcss-scss

**Comment by ben-eb** [comment]
I think we might have to look at bundling the scss syntax to fix https://github.com/ben-eb/perfectionist/issues/18. Not sure what happens down the line if/when new syntaxes are added, however.
