### ISSUE TITLE
@Include is combined with comment

### ISSUE THREAD

**Issue by akeroyd** [ben-eb/perfectionist#30]
Given the input:

```scss
a,a:visited{
  //@include border-radius(5px);
  @include transition(background-color 0.2s ease);
}
```

Perfectionist will return:
```scss
a, a:visited {
  //@includeborder-radius(5px)@include transition(background-color 0.2s ease);
}
```

**Comment by ben-eb** [comment]
I'm pretty sure that this was caused by the `format` option being set to `undefined`. Can you confirm with the latest release, please? 😃

**Comment by akeroyd** [comment]
Hi, sorry for the delay. Yes this seems fine in the latest version. Thanks for this project, it is very helpful!
